# Generated by Django 5.2.14 on 2026-06-04 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('file', models.FileField(upload_to='gallery/', verbose_name='Файл')),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('screenshot', 'Скріншот'), ('video', 'Відео')], default='photo', max_length=20, verbose_name='Тип медіа')),
                ('action_name', models.CharField(max_length=255, verbose_name='Назва події')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Схвалено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Медіа-матеріал',
                'verbose_name_plural': 'Медіа-матеріали',
                'ordering': ['-created_at'],
            },
        ),
    ]
