# Generated by Django 5.2.14 on 2026-06-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_game_name_to_action_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='category',
            field=models.CharField(choices=[('operation', 'Операція'), ('training', 'Тренування'), ('event', 'Подія'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Категорія'),
        ),
    ]
