# Generated by Django 6.0.4 on 2026-06-04 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cadet', 'Cadet'), ('instructor', 'Instructor'), ('admin', 'Admin')], default='cadet', max_length=20, verbose_name='Role')),
                ('codename', models.CharField(help_text='Unique operative alias (e.g. Ghost, Cipher, Nova)', max_length=64, unique=True, verbose_name='Codename')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Bio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
