# Generated by Django 5.2.14 on 2026-06-04 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "announcements",
            "0002_alter_announcement_author_alter_announcement_content_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Оголошення",
                "verbose_name_plural": "Оголошення",
            },
        ),
        migrations.AlterField(
            model_name="announcement",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата створення"
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="priority",
            field=models.CharField(
                choices=[
                    ("normal", "Звичайний"),
                    ("important", "Важливий"),
                    ("urgent", "Терміновий"),
                ],
                default="normal",
                max_length=10,
                verbose_name="Пріоритет",
            ),
        ),
    ]
