# Generated by Django 6.0.4 on 2026-05-27 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=64, unique=True, verbose_name="Кодове ім'я")),
                ('specialization', models.CharField(choices=[('planner', 'Планувальник'), ('hacker', 'Хакер'), ('master_of_disguise', 'Майстер маскування'), ('driver', 'Водій'), ('negotiator', 'Переговорник'), ('analyst', 'Аналітик'), ('gunsmith', 'Зброяр')], default='gunsmith', max_length=32, verbose_name='Спеціалізація')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Рівень')),
                ('bio', models.TextField(blank=True, verbose_name='Біографія')),
                ('skills', models.TextField(blank=True, verbose_name='Навички')),
                ('achievements', models.TextField(blank=True, verbose_name='Досягнення')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='portfolio/', verbose_name='Аватар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Досьє',
                'ordering': ['-level', 'codename'],
            },
        ),
    ]
